### ISSUE TITLE
Sort value always defaults to default

### ISSUE THREAD

**Issue by PeterWhiteGSA** [GSA/sam-design-system#745] opened 2021-07-08 17:48 UTC
When ever the search list loads the sort value is reset to the default in both the ngOnInit and ngOnChange:
![image](https://user-images.githubusercontent.com/84515469/124967086-a5fb0e80-dfe9-11eb-985a-6d40621efdc5.png)

This means that the sort value selected isn't saved when the user clicks back from a selection. This is mostly true on subdomains like Entity Information > Disaster Response Registry.

**Comment by yerramshilpa** [comment] 2021-07-20 14:09
The issue is resolved in @gsa-sam/layouts@10.0.34 version

**Closed by yerramshilpa** 2021-07-20 14:09 UTC
