### ISSUE TITLE
date-picker minDate validation issue

### ISSUE THREAD

**Issue by alexkamien** [GSA/sam-design-system#1116] opened 2023-02-03 17:25 UTC
**Components Involved**
formly component of type 'date-picker'

**Expected Behavior**
Allow the user to select the min-date set on the validation

**Actual Behavior**
Validation error displays, and does not allow user to select the min date set in validation

**Your Environment**
Angular Version: 13.3.11
@gsa-sam packages version: 13.0.5

**Ticket Number**
IAEMOD-4876

**Additional context**

min date is set as today's date. 
Validation displays correctly, but does not allow user to select today's date (Feb 3, 2023). 

<img width="878" alt="Screen Shot 2023-02-03 at 11 20 23 AM" src="https://user-images.githubusercontent.com/74928453/216667064-30739b3d-bcf5-46fd-99ca-d8e05d808f5d.png">

The calendar icon allows selection of today's date.

<img width="317" alt="Screen Shot 2023-02-03 at 11 24 29 AM" src="https://user-images.githubusercontent.com/74928453/216667542-86bc2df8-69aa-4189-a23b-d3473ec434a1.png">

config: 
 {
              key: 'endDate',
              type: 'datepicker',
              templateOptions: {
                label: 'End Date',
                hideOptional: true,
                required: true,
                minDate: new Date(),
                placeholder:
                'eg: ' +
                new Date().toLocaleString('en-US', {
                  month: 'short',
                  day: 'numeric',
                  year: 'numeric',
                }),
              },
            }

**Comment by yerramshilpa** [comment] 2023-05-01 20:17
The issue is fixed in @gsa-sam/sam-formly@14.0.0-beta.1 version

**Closed by yerramshilpa** 2023-05-01 20:17 UTC
