### ISSUE TITLE
Export SdsVideoPlayerComponet in component lib's barrel file

### ISSUE THREAD

**Issue by ascreven-gsa** [GSA/sam-design-system#381] opened 2020-10-06 17:56 UTC
I'm current trying to reference the SdsVideoPlayerComponent in a TypeScript file; however, am getting errors that it's not found. I tested with the SdsAutocompleteComponent which is exported in the public-api.ts and it works as expected. 
https://github.com/nrwl/nx/issues/1533

**Comment by davereed** [comment] 2020-10-06 18:00
Did you import the video module to your module?

**Comment by ascreven-gsa** [comment] 2020-10-07 13:32
Yes, and tried to import the video component but it wasn't found.

**Comment by davereed** [comment] 2020-10-07 15:05
Right now we only export the component individually if it is being extended or used somewhere else in SDS. I think we may start exporting a lot more from all components, but do you actually need to import the component for your story? If you are only using it in your components template, including the video module in your module should suffice.

**Comment by ascreven-gsa** [comment] 2020-10-07 15:14
Yes, I was trying to pull the component into a ts file. I found a workaround to finish my story but it would still be nice to have

**Comment by yerramshilpa** [comment] 2020-10-29 19:01
The issue is resolved in @gsa-sam/components@0.6.28 version

**Closed by yerramshilpa** 2020-10-29 19:01 UTC
