### ISSUE TITLE
formly-form tooltip Margin / Position Customization 

### ISSUE THREAD

**Issue by wonko-gsa** [GSA/sam-design-system#1478] opened 2024-06-07 15:21 UTC
**Components Involved**
formly-form tooltip

**Expected Behavior**
The tooltip icon to be placed at the end of the string like: `Are you a successor to a predecessor that held a federal contract or grant within the last 3 years? **( i )**` instead far off.
So, it will be nice if we can place the tooltip icon at the end of the string as if it is a part of the sentence.

**Actual Behavior**
The tooltip icon is placed either in the next line, or next block of the text (but not at the end of the string)
In mobile view, the tooltip icon is place in the next line and it is very close to the radio options in the next line. (no margin bottom for the tooltip icon.)

- Mobile View: ![image](https://github.com/GSA/sam-design-system/assets/117218338/d0c3b2d1-8b71-48e2-97ee-9c5567c70802)
- Desktop/Tablet View 
![image](https://github.com/GSA/sam-design-system/assets/117218338/fe74eabf-6a0c-46ad-94eb-1c3e6f6b852e)

**Your Environment**
```
  Angular Version: 17.3
    "@gsa-sam/components": "17.0.6",
    "@gsa-sam/layout": "17.0.2",
    "@gsa-sam/layouts": "17.0.2",
    "@gsa-sam/ngx-uswds": "17.0.1",
    "@gsa-sam/ngx-uswds-icons": "17.0.0",
    "@gsa-sam/sam-formly": "17.0.6",
    "@gsa-sam/sam-material-extensions": "17.0.6",
    "@gsa-sam/sam-styles": "3.0.18",
    "@gsa-sam/shared": "17.0.2",
```

**Is your feature request related to a problem? Please describe.**
We were able to make the tooltip icon to be placed near the text using `display-inline` class for desktop view and tablet view (not at the end of the string as if it is a part of the sentence). 
However, the tooltip icon in mobile view does not have a margin bottom.

**Describe the desired solution**
If we are allowed to customize the style of icon in the frontend, that will be nice. 
If we can control the position of the icon or the margins to align with text, that will be nice. So we can place the icon at the end of a sentence as if the icon is a part of the text. 

**Ticket Number**
IAEMOD-30520

**Additional context**

- FormlyFieldConfig snippet:
```
 cageNcageInput: FormlyFieldConfig[] = [
    {
      key: 'hasPredecessor',
      type: 'radio',
      className: 'desktop:grid-col-7 tablet:grid-col-12 display-inline',
      props: {
        labelClass: 'grid-row margin-bottom-1',
        required: true,
        label: `Are you a successor to a predecessor that held a federal contract or grant within the last 3 years?`,
        tooltipText: 
          `
              A predecessor is an entity that is replaced by a successor and includes any predecessors of the predecessor.
              <br><br>
              A successor acquires the assets and carries out the affairs of the predecessor under a new name, often through acquisition or merger. A successor is not a new office or division of the same company or a company that only changes its name. The extent of the successor's responsibility for the predecessor's liabilities may vary, depending on state law and specific circumstances. 
              <a class="usa-link" href=${FAR_52_204_20_URL} target="_blank" rel="noopener noreferrer">(FAR 52.204-20)</a>
          `,
        tooltipClass: ModuleSharedHelper.TOOLTIP_TEXT_STYLE_CLASSES,
        options: [
          { value: 'Y', label: 'Yes' },
          { value: 'N', label: 'No' }
        ],
      },
```

**Comment by yerramshilpa** [comment] 2024-09-05 12:24
The issue is resolved in @gsa-sam/sam-formly@17.0.8

**Closed by yerramshilpa** 2024-09-05 12:24 UTC
