### ISSUE TITLE
[Entity Registration Modules MVP] Clearing Formly input using 'x' icon is not setting dirty flag

### ISSUE THREAD

**Issue by brandydanner-gsa** [GSA/sam-design-system#1542] opened 2024-09-26 15:23 UTC
**Components Involved**
Formly input field 

**Expected Behavior**
I'm wanting to use the `dirty` property to check if the user has unsaved changes so that I can pop up a confirmation that they're okay to navigate away and lose their changes.  When using the "x" clear button on a Formly input field, I expect the `dirty` flag to be set on the formControl.

**Actual Behavior**
In the stepper, I'm not seeing the formControl marked as dirty if I use the "x" clear button to remove the value on the Formly input field.  If I backspace to remove the value, I do see it marked as dirty. 

**Your Environment**
Angular Version: ^17.3.7

    "@gsa-sam/components": "17.0.10",
    "@gsa-sam/layout": "17.0.12",
    "@gsa-sam/layouts": "17.0.5",
    "@gsa-sam/ngx-uswds": "17.0.1",
    "@gsa-sam/ngx-uswds-icons": "17.0.0",
    "@gsa-sam/sam-formly": "17.0.10",
    "@gsa-sam/sam-material-extensions": "17.0.10",
    "@gsa-sam/sam-styles": "3.0.20",
    "@gsa-sam/shared": "17.0.12",

**Ticket Number**
IAEMOD-26747

**Additional context**
In my custom stepper, using this check:

hasUnsavedChanges(): boolean {
    return this.selectedStep?.fieldConfig?.formControl?.dirty;
  }

**Comments from Shilpa:**
"When using FormControl.setValue() in Angular's Reactive Forms, it doesn't mark the control as dirty by default. The "dirty" state in Angular Reactive Forms is set when the value of the control is changed by user interaction, not programmatically. However, if you want to make the control dirty programmatically, you can manually set it using the markAsDirty() method."
So we need to manually update

**Comment by yerramshilpa** [comment] 2024-11-08 05:03
The issue is resolved in @gsa-sam/sam-formly": "17.0.12"

**Closed by yerramshilpa** 2024-11-08 05:03 UTC
