### ISSUE TITLE
Unable to type in textarea when there is no `maxLength` props added

### ISSUE THREAD

**Issue by wonko-gsa** [GSA/sam-design-system#1400] opened 2024-01-23 20:09 UTC
**Components Involved**
textarea

**Expected Behavior**
Users should be able to type in the field even if there is no `maxLength` props as previously worked before Formly v.6 upgrade.

**Actual Behavior**
I cannot type anything in the textarea field without `maxLength` props. 

**Your Environment**
Angular Version: 16.2.12
@gsa-sam packages version: 
```
    "@gsa-sam/components": "16.0.10",
    "@gsa-sam/layout": "16.0.8",
    "@gsa-sam/layouts": "16.0.0",
    "@gsa-sam/ngx-uswds": "16.0.1",
    "@gsa-sam/ngx-uswds-icons": "16.0.0",
    "@gsa-sam/sam-formly": "16.0.10",
    "@gsa-sam/sam-material-extensions": "16.0.10",
    "@gsa-sam/sam-styles": "3.0.18",
    "@gsa-sam/shared": "16.0.8",
    "@ngx-formly/core": "6.2.1",
```

**Ticket Number**
IAEMOD-24737

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.
```
    {
      fieldGroupClassName: 'grid-row',
      key: 'comments',
      type: 'textarea',
      props: {
        required: true,
        label: 'Comments',
      }
    }
```

**Comment by yerramshilpa** [comment] 2024-01-24 20:58
The issue is resolved in sam-formly@16.0.11

**Closed by yerramshilpa** 2024-01-24 20:58 UTC
