### ISSUE TITLE
Extra API calls and subscription triggers when (filterChange) event is used

### ISSUE THREAD

**Issue by KidanyGSA** [GSA/sam-design-system#356] opened 2020-09-15 18:25 UTC
Currently we only trigger API calls to SerachAPI inside the getData() function, recently we added filterChange event as a way to detect if a keyword is being search and manually update the sorting option to "relevance". This is causing a side effect where having this event is triggering extra API calls and we can see the subscription code executed 3 times per filter change.

![image](https://user-images.githubusercontent.com/66032295/93249423-49c7b500-f75f-11ea-8ca6-ec728e1f4739.png)

**Comment by yerramshilpa** [comment] 2020-09-29 14:09
The issue is resolved in the @gsa-sam/sam-formly@0.6.26 version.

**Closed by yerramshilpa** 2020-09-29 14:09 UTC
