### ISSUE TITLE
508 compliance issues on the Input field label and description

### ISSUE THREAD

**Issue by navyasreekumbam-reisys** [GSA/sam-design-system#1026] opened 2022-08-09 15:54 UTC
On "Enter Entity Information" page the text "Doing business As (Optional)" and the text right below were skipped using JAWS. By tabbing, it went from Legal Business Name input box directly to the next input box. It skipped the text in between. 

On "Enter Entity Information" page the text "Physical Address" is skipped. Likely tabbing order is incorrect.

**Comment by yerramshilpa** [comment] 2022-08-10 13:25
@navyasreekumbam-reisys  the issue is resolved and released in sam-formly@12.0.10 version. just need to update the version not need to make any code change on your end.

**Closed by yerramshilpa** 2022-08-10 13:25 UTC
