### ISSUE TITLE
508 Issue on Autocomplete Multiple Selection Mode

### ISSUE THREAD

**Issue by wonko-gsa** [GSA/sam-design-system#1483] opened 2024-06-24 14:14 UTC
**Components Involved**
Autocomplete - Multiple Selection Mode

**Actual Behavior**
Found 508 issue with Access Assistant on multi selection mode for autocomplete as shown in the screenshot: 
```
This UL with a role attribute value of 'listbox' should not contain input elements (without an assigned ARIA role), button elements (without an assigned ARIA role), textarea elements (without an assigned ARIA role), select elements (without an assigned ARIA role) or A elements (without an assigned ARIA role)
```
- localhost:
![image](https://github.com/GSA/sam-design-system/assets/117218338/a3cd915b-a920-48e9-8504-5c8e8ecb8370)
![image](https://github.com/GSA/sam-design-system/assets/117218338/d19b0291-38df-441f-9621-e34538474f56)

- SDS Storybook:
 https://gsa.github.io/sam-design-system/?path=/story/components-autocomplete--selection-mode
![image](https://github.com/GSA/sam-design-system/assets/117218338/f46bdf4f-67f8-4f82-b041-ad607fe223eb)
![image](https://github.com/GSA/sam-design-system/assets/117218338/a43de91f-ad3d-4a12-88f5-945bf0732669)

**Your Environment**
Angular Version: 17.3.7
    "@gsa-sam/components": "17.0.6",
    "@gsa-sam/layout": "17.0.3",
    "@gsa-sam/layouts": "17.0.3",
    "@gsa-sam/ngx-uswds": "17.0.1",
    "@gsa-sam/ngx-uswds-icons": "17.0.0",
    "@gsa-sam/sam-formly": "17.0.6",
    "@gsa-sam/sam-material-extensions": "17.0.6",
    "@gsa-sam/sam-styles": "3.0.18",
    "@gsa-sam/shared": "17.0.3",

**Ticket Number**
IAEMOD-28772

**Comment by yerramshilpa** [comment] 2024-09-20 14:48
The issue is resolved in @gsa-sam/components@17.0.10

**Closed by yerramshilpa** 2024-09-20 14:48 UTC
