### ISSUE TITLE
History Tracking - SDS Filter - Reset is not clearing URL parameters

### ISSUE THREAD

**Issue by puspendupalgsa** [GSA/sam-design-system#380] opened 2020-10-06 14:51 UTC
When "Reset" icon is clicked, the URL parameters related to history tracking in SDS Filter is not clearing.

**Comment by yerramshilpa** [comment] 2020-10-29 19:00
The issue is resolved in @gsa-sam/sam-formly@0.6.28 version

**Closed** 2020-10-29 19:01 UTC
