### ISSUE TITLE
dateRangePicker -> hideOptional not working

### ISSUE THREAD

**Issue by jesseboydgsa** [GSA/sam-design-system#642] opened 2021-03-17 16:22 UTC
**Components Involved**
Please list the common component(s) involved that you're experiencing an issue with
dateRangePicker

**Expected Behavior**
How you expect the listed component(s) to function
hideOptional = true -> i expect to not see optional

**Actual Behavior**
How the listed component(s) actually function
![image](https://user-images.githubusercontent.com/58823468/111501203-021be900-8702-11eb-9e83-a042657c3926.png)

**Your Environment**
Angular Version: X.Y.Z
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)
![image](https://user-images.githubusercontent.com/58823468/111501333-1f50b780-8702-11eb-8799-1ac5fee38ea7.png)

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAE-XYZ
IAEDEV-49078

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

**Comment by jesseboydgsa** [comment] 2021-03-17 16:30
![image](https://user-images.githubusercontent.com/58823468/111502758-60959700-8703-11eb-85e4-56c0c055adf5.png)

**Comment by yerramshilpa** [comment] 2021-03-23 17:30
@jesseboydgsa  The issue is resolved in @gsa-sam/components@10.0.17

**Closed** 2021-03-30 19:50 UTC
Labels: bugfix
