### ISSUE TITLE
'usa-sr'only' makes the label hidden but leaves space

### ISSUE THREAD

**Issue by jmohanta-REISys** [GSA/sam-design-system#900] opened 2022-01-24 21:49 UTC
[**Components](url) Involved**

**Expected Behavior**
There should not be any space

**Actual Behavior**

**Your Environment**
155COMP
Angular Version: X.Y.Z
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)

**Ticket Number**
IAEDEV-63381

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

![image (3)](https://user-images.githubusercontent.com/52080001/150869811-fedc689a-ea8b-4850-b909-7666e5604443.png)
![image(11)](https://user-images.githubusercontent.com/52080001/150870595-efc2dfe3-7218-4383-97ff-d69153d3f6b5.png)

**Comment by Bibek-Regmi** [comment] 2022-01-27 21:32
Issue resolved in this merge - https://github.com/GSA/sam-styles/pull/519
The spacing under Filter By on the collapsible card is expected. It is by design and not an issue.
The pacing at the bottom on 'Core Data Availability' panel will be resolved with sam styles v0.0.130

**Comment by cwolf10** [comment] 2022-02-17 19:47
Spacing reduced with [v0.0.130](https://github.com/GSA/sam-styles/releases/tag/v0.0.130). Any remaining spacing is by design and not tied to `labelClass: 'usa-sr-only'`

**Closed by cwolf10** 2022-02-17 19:47 UTC
