### ISSUE TITLE
Text not being cleared tag is created in sds-search-autocomplete component

### ISSUE THREAD

**Issue by knamburigsa** [GSA/sam-design-system#1500] opened 2024-08-09 12:40 UTC
**Components Involved**
sds-search-autocomplete
https://github.com/GSA/sam-design-system/blob/0aad377c02719bfceef80a6874e48c4a554d8d33/libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts

**Expected Behavior**
How you expect the listed component(s) to function
1. Navigate to https://gsa.github.io/sam-design-system/?path=/story/components-autocomplete--free-text
2. In tagMode demo text input.
![image](https://github.com/user-attachments/assets/634d2f07-41d6-4688-ae76-c8fc660e7ac5)
3. When I type some text and press enter then text in the input field should be cleared and the tag should be added.

**Actual Behavior**
How the listed component(s) actually function
1. Navigate to https://gsa.github.io/sam-design-system/?path=/story/components-autocomplete--free-text
2. In tagMode demo text input.
![image](https://github.com/user-attachments/assets/1afd700a-0bf1-4eda-b755-a23bbb40249e)
3. When I type some text and press enter, text input is not cleared after adding the tag.

**Your Environment**
Angular Version: X.Y.Z
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)
![image](https://github.com/user-attachments/assets/b2495928-aa24-4208-9067-22a903cb4a03)

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAEMOD-32459

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.
https://gsa.github.io/sam-design-system/assets/stackblitzes/autocomplete/autocomplete-free-text/stackblitz.html
https://gsa.github.io/sam-design-system/?path=/story/components-autocomplete--free-text

**Comment by yerramshilpa** [comment] 2024-09-05 12:21
The issue is resolved and released in @gsa-sam/components@17.0.8

**Closed by yerramshilpa** 2024-09-05 12:21 UTC
