### ISSUE TITLE
History: not clearing the url parameter when a filter chip is removed

### ISSUE THREAD

**Issue by KidanyGSA** [GSA/sam-design-system#355] opened 2020-09-15 18:07 UTC
Keywords and type of notice chips are removed
![image](https://user-images.githubusercontent.com/66032295/93247734-bc836100-f75c-11ea-9730-5f094f47a294.png)

**Comment by KidanyGSA** [comment] 2020-10-01 21:52
Maybe this error will help
![image](https://user-images.githubusercontent.com/66032295/94867226-d389aa80-040e-11eb-8f0e-8383afc7fff9.png)

**Comment by yerramshilpa** [comment] 2020-10-29 19:00
The issue is resolved in @gsa-sam/sam-formly@0.6.28 version

**Closed by yerramshilpa** 2020-10-29 19:00 UTC
